services:
  # Database Migration Service
  migrate:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        echo '🔄 Checking database migrations...' &&
        npx prisma migrate status &&
        if npx prisma migrate status | grep -q 'Database schema is up to date'; then
          echo '✅ Database already up to date, skipping migrations'
        else
          echo '🔄 Running database migrations...' &&
          npx prisma migrate deploy &&
          echo '✅ Migrations completed!'
        fi
      "
    restart: "no"
    networks:
      - app-network

  # Seed Service (เฉพาะ development และเมื่อไม่มีข้อมูล)
  seed:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=${NODE_ENV:-development}
      - SKIP_SEED=${SKIP_SEED:-false}
    depends_on:
      migrate:
        condition: service_completed_successfully
    command: >
      sh -c "
        if [ \"$$NODE_ENV\" = \"development\" ] && [ \"$$SKIP_SEED\" != \"true\" ]; then
          echo '🔍 Checking if database needs seeding...' &&
          USER_COUNT=$$(npx prisma db execute --command=\"SELECT COUNT(*) FROM \\\"User\\\";\" 2>/dev/null | tail -1 | grep -o '[0-9]*' || echo '0') &&
          if [ \"$$USER_COUNT\" -eq 0 ]; then
            echo '🌱 Database is empty, seeding...' &&
            npm run seed &&
            echo '✅ Seeding completed!'
          else
            echo '✅ Database already has data ($$USER_COUNT users), skipping seed'
          fi
        else
          echo '⏭️ Skipping seed (production or SKIP_SEED=true)'
        fi
      "
    restart: "no"
    networks:
      - app-network
    profiles:
      - development

  # Main Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-development}
    ports:
      - "${API_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=${REDIS_HOST:-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-here}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-7d}
      - JWT_EXPIRATION_SECONDS=${JWT_EXPIRATION_SECONDS:-604800}
      # 🔥 NEW: Cookie configuration
      - COOKIE_DOMAIN=
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api
      # Cloudinary
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      # Email
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - APP_NAME=${APP_NAME:-SeeU Cafe}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3001}
      # Social Auth
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
      - FACEBOOK_APP_SECRET=${FACEBOOK_APP_SECRET}
      # Push Notifications
      - VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - VAPID_SUBJECT=${VAPID_SUBJECT}
      # Webhooks
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - N8N_PICKUP_WEBHOOK_URL=${N8N_PICKUP_WEBHOOK_URL}
      - N8N_RECEIPT_WEBHOOK_URL=${N8N_RECEIPT_WEBHOOK_URL}
      - N8N_TABLE_WEBHOOK_URL=${N8N_TABLE_WEBHOOK_URL}
      # Receipt Configuration
      - RECEIPT_LOGO_URL=${RECEIPT_LOGO_URL}
      - RECEIPT_FOOTER_TEXT=${RECEIPT_FOOTER_TEXT}
      - COMPANY_NAME=${COMPANY_NAME}
      - COMPANY_ADDRESS=${COMPANY_ADDRESS}
      - COMPANY_PHONE=${COMPANY_PHONE}
      - COMPANY_EMAIL=${COMPANY_EMAIL}
      - COMPANY_WEBSITE=${COMPANY_WEBSITE}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    volumes:
      # 🔥 FIX: เฉพาะ development เท่านั้นที่ bind mount source code
      - type: bind
        source: .
        target: /app
        bind:
          create_host_path: true
      # 🔥 CRITICAL: Anonymous volume สำหรับ node_modules เพื่อไม่ให้ถูก override
      - /app/node_modules
      # 🔥 FIX: Uploads volume - ใช้ named volume แทน
      - uploads-data:/app/uploads
      # 🔥 FIX: Templates volume
      - ./templates:/app/templates:ro
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api"] 
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL Database
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-seeu_cafe}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
      # 🔥 FIX: เพิ่ม config สำหรับความเสถียร
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      # 🔥 CRITICAL: ใช้ named volume สำหรับข้อมูล PostgreSQL
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-seeu_cafe}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis Cache
  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT_EXTERNAL:-6379}:6379"
    command: redis-server --appendonly yes --save 60 1000
    volumes:
      # 🔥 CRITICAL: ใช้ named volume สำหรับข้อมูล Redis
      - redis-data:/data
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

  # PGAdmin (เฉพาะ development)
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin123}
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      # 🔥 NEW: เพิ่ม volume สำหรับ PGAdmin config
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network
    restart: unless-stopped
    profiles:
      - development

  # n8n Automation (optional)
  n8n:
    image: n8nio/n8n
    ports:
      - "${N8N_PORT:-5678}:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=${N8N_AUTH_ACTIVE:-true}
      - N8N_BASIC_AUTH_USER=${N8N_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_AUTH_PASSWORD:-password123}
      - TZ=${TZ:-Asia/Bangkok}
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
    volumes:
      # 🔥 CRITICAL: ใช้ named volume สำหรับข้อมูล n8n
      - n8n-data:/home/node/.n8n
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    profiles:
      - development

networks:
  app-network:
    driver: bridge

volumes:
  # 🔥 CRITICAL: ทุก volumes เป็น named volumes เพื่อความเสถียร
  postgres-data:
    driver: local
  redis-data:
    driver: local
  n8n-data:
    driver: local
  uploads-data:
    driver: local
  pgadmin-data:
    driver: local